#!/system/bin/sh
# Made by Ayush Rathore
# Credits to Shoaib Anwar a.k.a Shoaib0597.

# Stop Logging Process to Reduce CPU-Load---
stop logd

# kCAL settings for more vibrancy and better colour reproduction
echo 33 > /sys/devices/platform/kcal_ctrl.0/kcal_min
echo 273 > /sys/devices/platform/kcal_ctrl.0/kcal_sat
echo 252 > /sys/devices/platform/kcal_ctrl.0/kcal_val
echo 258 > /sys/devices/platform/kcal_ctrl.0/kcal_cont


# Set Minimum CPU-Frequency to 100MHz for big and LITTLE Cluster---
echo 1 > /sys/devices/system/cpu/cpu0/online
echo 100000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 1 > /sys/devices/system/cpu/cpu4/online
echo 100000 > /sys/devices/system/cpu/cpu4/cpufreq/scaling_min_freq


# Enable and Configure Interactive Governor for big Cluster---
echo 1 > /sys/devices/system/cpu/cpu0/online
echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "20000 1200000:50000" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/above_hispeed_delay
echo 85 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/go_hispeed_load 
echo 50000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/timer_rate
echo 100000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/timer_slack  
echo 1350000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/hispeed_freq 
echo 0 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/io_is_busy
echo 1 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/fast_ramp_down
echo 50000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/boostpulse_duration
echo "1 800000:85 1200000:90" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/target_loads 
echo 50000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/min_sample_time


# Enable and Configure Interactive Governor for LITTLE Cluster---
echo 1 > /sys/devices/system/cpu/cpu4/online
echo "interactive" > /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
echo "20000 1000000:50000" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/above_hispeed_delay
echo 85 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/go_hispeed_load 
echo 50000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/timer_rate
echo 100000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/timer_slack 
echo 1200000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/hispeed_freq 
echo 0 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/io_is_busy
echo 1 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/fast_ramp_down
echo 50000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/boostpulse_duration
echo "1 800000:85 1000000:90" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/target_loads 
echo 50000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/min_sample_time

# Misc
echo 128 > /proc/sys/kernel/random/read_wakeup_threshold
echo 256 > /proc/sys/kernel/random/write_wakeup_threshold

#Safetynet
chmod 640 /sys/fs/selinux/enforce
chmod 440 /sys/fs/selinux/policy
