#!/system/bin/sh
# Made by Ayush Rathore

# Stop Logging Process to Reduce CPU-Load---
stop logd

#Default temp limit
echo 40 > /sys/module/msm_thermal/parameters/temp_threshold

# kCAL settings for more vibrancy and better colour reproduction---
echo 33 > /sys/devices/platform/kcal_ctrl.0/kcal_min
echo 273 > /sys/devices/platform/kcal_ctrl.0/kcal_sat
echo 252 > /sys/devices/platform/kcal_ctrl.0/kcal_val
echo 258 > /sys/devices/platform/kcal_ctrl.0/kcal_cont


# Set Minimum CPU-Frequency to 200MHz---
echo 1 > /sys/devices/system/cpu/cpu0/online
echo 200000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq


# Enable and Configure Interactive Governor---
echo 1 > /sys/devices/system/cpu/cpu0/online
echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "20000 1200000:50000" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/above_hispeed_delay
echo 95 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/go_hispeed_load 
echo 20000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/timer_rate
echo 20000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/timer_slack  
echo 1200000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/hispeed_freq 
echo 0 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/io_is_busy
echo 1 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/fast_ramp_down
echo 0 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/boostpulse_duration
echo "1 800000:85 1000000:90" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/target_loads 
echo 40000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/min_sample_time

# Entropy---
echo 128 > /proc/sys/kernel/random/read_wakeup_threshold
echo 256 > /proc/sys/kernel/random/write_wakeup_threshold

